# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-08 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='seat_type',
            field=models.SmallIntegerField(choices=[(1, 'Bar Stool'), (2, 'Window Seat'), (3, 'Booth'), (4, 'Table')], default=1),
        ),
    ]
