# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-13 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20200710_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='email',
        ),
    ]
