# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-30 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20200713_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reserved_end_time',
            new_name='booking_end_time',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='reserved_start_time',
            new_name='booking_start_time',
        ),
    ]
