# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-31 17:35
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20200731_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(error_messages={'invalid': 'Enter a valid phone number (e.g. +353861234567)'}, max_length=128, region=None),
        ),
    ]
