# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-01 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20200731_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='full_name',
            field=models.CharField(max_length=20),
        ),
    ]
