# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-07 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='county',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='order',
            name='street_address1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='street_address2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='town_or_city',
        ),
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.SmallIntegerField(choices=[('1', 'Stool No.1'), ('2', 'Stool No.2'), ('3', 'Stool No.3'), ('4', 'Stool No.4'), ('5', 'Stool No.5'), ('6', 'Window No.1'), ('7', 'Window No.2'), ('8', 'Window No.3'), ('9', 'Window No.4'), ('10', 'Window No.5'), ('11', 'Booth No.1'), ('12', 'Booth No.2'), ('13', 'Booth No.3'), ('14', 'Booth No.4'), ('15', 'Booth No.5'), ('16', 'Table No.1'), ('17', 'Table No.2'), ('18', 'Table No.3'), ('19', 'Table No.4'), ('20', 'Table No.5')], default='1'),
        ),
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
