# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-01 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20200708_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(error_messages={'invalid': 'Enter a valid phone number (e.g. +353861234567)'}, max_length=128, region=None),
        ),
    ]
